# Generated by Django 3.2.16 on 2022-11-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dishes',
        ),
        migrations.CreateModel(
            name='OrderAndDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.dish', verbose_name='Блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ и блюдо',
                'verbose_name_plural': 'Заказы и блюда',
            },
        ),
    ]
