version: '3.7'

volumes:
  postgres_data:

services:
  django:
    container_name: django
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
      args:
        MODE: "--with dev"
        APP_HOME: "/server"
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:8000"
    volumes:
      - ./server:/server
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - DJANGO_DEBUG=${DJANGO_DEBUG}

  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  
  redis:
    image: redis:6
    container_name: redis
    restart: always
    expose:
      - 6379

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: swagger-editor
    restart: always
    ports:
      - "5050:8080"

  alexandria:
    image: raisultan/alexandria:0.1
    container_name: alexandria
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./alexandria/ws.yml:/ws.yml
    environment:
      - ALEXANDRIA_YAML=/ws.yml
