version: '3.7'

volumes:
  postgres_data:

services:
  django:
    container_name: django
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
      args:
        MODE: "--with dev"
        APP_HOME: "/server"
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - REDIS_URL=${REDIS_URL}
      - FCM_SERVER_KEY=${FCM_SERVER_KEY}
    command: ["make", "run-django-dev"]

  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  celery_worker:
    container_name: celery_worker
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
      args:
        MODE: "--with dev"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
      - FCM_SERVER_KEY=${FCM_SERVER_KEY}
    command: celery --app=config worker --loglevel=DEBUG

  celery_beat:
    container_name: celery_beat
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
      args:
        MODE: "--with dev"
    depends_on:
      - postgres
      - redis
      - celery_worker
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
      - FCM_SERVER_KEY=${FCM_SERVER_KEY}
    command: celery --app=config beat --scheduler=django --loglevel=DEBUG
  
  flower:
    container_name: flower
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
      args:
        MODE: "--with dev"
    ports:
      - "5555:5555"
    depends_on:
      - postgres
      - redis
      - celery_worker
      - celery_beat
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
      - FCM_SERVER_KEY=${FCM_SERVER_KEY}
    command: celery --app=config flower

  redis:
    image: redis:6
    container_name: redis
    restart: always

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: swagger-editor
    restart: always
    ports:
      - "5050:8080"

  alexandria:
    image: raisultan/alexandria:0.1
    container_name: alexandria
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./alexandria/ws.yml:/ws.yml
    environment:
      - ALEXANDRIA_YAML=/ws.yml
