version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  media_volume:

services:
  nginx:
    restart: always
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - django
    ports:
      - 80:80
    volumes:
      - media_volume:/server/media

  django: &django
    build:
      context: .
      dockerfile: ./server/compose/production/django/Dockerfile
    image: emenu_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./server/.envs/.django
      - ./server/.envs/.postgres
    expose:
      - 8000
    volumes:
      - media_volume:/server/media
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./server/compose/production/postgres/Dockerfile
    image: emenu_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./server/.envs/.postgres

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: emenu_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: emenu_production_celerybeat
    command: /start-celerybeat