version: '3'

volumes:
  postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./server/compose/local/django/Dockerfile
    image: emenu_local_django
    container_name: emenu_local_django
    depends_on:
      - postgres
    volumes:
      - ./server:/server
    env_file:
      - ./server/.envs/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:14.4
    container_name: emenu_local_postgres
    volumes:
       - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./server/.envs/.postgres

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "80:8080"