version: '3'

volumes:
  postgres_data:

services:
  django:
    container_name: django
    build:
      context: ./server
      dockerfile: ./Dockerfile
      args:
        MODE: "--with dev"
    depends_on:
      - postgres
    volumes:
      - ./server:/server
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: postgres
    image: postgres:14.4
    ports:
      - "5432:5432"
    volumes:
       - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: swagger-editor
    ports:
      - "80:8080"
