version: '3'

volumes:
  postgres_data:

services:
  nginx:
    image: ghcr.io/emenu124ru/nginx:latest
    restart: always
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - django
      - daphne
      - alexandria
    ports:
      - 80:80
    volumes:
      - ./server/media:/nginx/media/
  
  daphne:
    image: ghcr.io/emenu124ru/django:latest
    restart: always
    container_name: daphne
    build:
      context: ./server/
      dockerfile: Dockerfile
      args:
        MODE: "--without dev"
        APP_HOME: "/server"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_URL=${REDIS_URL}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    expose:
      - 8008
    command: daphne -b 0.0.0.0 -p 8008 config.asgi:application

  django:
    image: ghcr.io/emenu124ru/django:latest
    restart: always
    container_name: django
    build:
      context: ./server/
      dockerfile: Dockerfile
      args:
        MODE: "--without dev"
        APP_HOME: "/server"
    depends_on:
      - postgres
      - redis
    expose:
      - 8000
    volumes:
      - ./server/media:/server/media/
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ADMIN_URL=${DJANGO_ADMIN_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    command: gunicorn config.wsgi -c ./config/gunicorn.py

  redis:
    container_name: redis
    restart: always
    image: redis:6
    expose:
      - 6379

  postgres:
    restart: always
    container_name: postgresql
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dumps:/dumps
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  postgres-backup:
    image: rmiddle/pg_dump:latest
    container_name: postgres-backup
    links:
      - postgres
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDB=${POSTGRES_DB}
      - PGHOST=${POSTGRES_HOST}
      - CRON_SCHEDULE=0 0 * * 0
      - DELETE_OLDER_THAN=3
    volumes:
      - ./dumps:/dump
    command: dump-cron

  alexandria:
    image: raisultan/alexandria:0.1
    container_name: alexandria
    volumes:
      - ./docs/ws.yml:/ws.yml
    ports:
      - "8080:8080"
    environment:
      - ALEXANDRIA_YAML=/ws.yml

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    expose:
      - 5050
    volumes:
      - ./docs/openapi.yaml:/openapi.yaml
    environment:
      - SWAGGER_JSON=/openapi.yaml
      - PORT=5050
