version: '3'

volumes:
  emenu_local_postgres_data: {}
  emenu_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./server/compose/local/django/Dockerfile
    image: emenu_local_django
    container_name: emenu_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/server
    env_file:
      - ./server/.envs/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./server/compose/production/postgres/Dockerfile
    image: emenu_production_postgres
    container_name: emenu_local_postgres
    volumes:
      - emenu_local_postgres_data:/var/lib/postgresql/data:Z
      - emenu_local_postgres_data_backups:/backups:z
    env_file:
      - ./server/.envs/.postgres

  redis:
    image: redis:6
    container_name: emenu_local_redis

  celeryworker:
    <<: *django
    image: emenu_local_celeryworker
    container_name: emenu_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: emenu_local_celerybeat
    container_name: emenu_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "80:8080"