# Generated by Django 4.2 on 2024-03-02 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.CreateModel(
            name='TagToPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тэг для места',
                'verbose_name_plural': 'Тэги для места',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Время начала работы')),
                ('time_finish', models.TimeField(verbose_name='Время окончания работы')),
                ('week_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='День недели')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='restaurants.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Расписание работы ресторана',
                'verbose_name_plural': 'Расписания работы ресторанов',
                'unique_together': {('week_day', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=16, verbose_name='Название места')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='restaurants.restaurant', verbose_name='Ресторан')),
                ('tags', models.ManyToManyField(related_name='places', to='restaurants.tagtoplace', verbose_name='Тэги к столу')),
            ],
            options={
                'verbose_name': 'Место в ресторане',
                'verbose_name_plural': 'Места в ресторане',
                'unique_together': {('place', 'restaurant')},
            },
        ),
    ]
