# Generated by Django 3.2.16 on 2023-12-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('week_day', 'restaurant')},
        ),
    ]
