# Generated by Django 3.2.16 on 2023-10-19 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='reviews',
            field=models.ManyToManyField(related_name='restaurant', to='reviews.Review', verbose_name='Отзыв'),
        ),
        migrations.AddField(
            model_name='place',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='restaurants.restaurant', verbose_name='Ресторан'),
        ),
    ]
