# Generated by Django 4.2 on 2024-06-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='timezone',
            new_name='time_zone',
        ),
    ]
