# Generated by Django 3.2.16 on 2023-10-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagToPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тэг для места',
                'verbose_name_plural': 'Тэги для места',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(related_name='places', to='restaurants.TagToPlace', verbose_name='Тэги к столу'),
        ),
    ]
