# Generated by Django 4.2 on 2024-06-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_timezone_restaurant_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtoplace',
            name='type',
            field=models.CharField(choices=[('LOCATION', 'Местоположение'), ('NUMBER_OF_SEATS', 'Количество мест')], default='LOCATION', max_length=16, verbose_name='Тип тэга'),
        ),
    ]
