# Generated by Django 3.2.16 on 2022-10-14 14:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('WAITER', 'Waiter'), ('BARTENDER', 'Bartender'), ('COOK', 'Cook'), ('CHEF', 'Chef'), ('MANAGER', 'Manager'), ('HOSTESS', 'Hostess')], max_length=64, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonuses', models.PositiveIntegerField(verbose_name='Бонусы')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть введен в формате: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефонный номер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
