# Generated by Django 3.2.16 on 2022-11-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('WAITER', 'Официант'), ('BARTENDER', 'Бармен'), ('COOK', 'Повар'), ('CHEF', 'Шеф-повар'), ('MANAGER', 'Управляющий'), ('HOSTESS', 'Хостес')], max_length=64, verbose_name='Роль'),
        ),
    ]
