apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: emenu
spec:
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres:14.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: db-credentials
        volumeMounts:
          - mountPath: /var/lib/postgres/data
            name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: postgres-pvc
