apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: emenu
  labels:
    app: postgres-svc
spec:
  type: ClusterIP
  selector:
    app: postgresdb
  ports:
    - port: 5432
      targetPort: 5432
