# Generated by Django 3.2.16 on 2023-12-03 02:14

import apps.orders.models.dish
import apps.orders.models.reservation
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('compound', models.TextField(verbose_name='Состав')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.orders.models.dish.get_directory_path, verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка блюда',
                'verbose_name_plural': 'Картинки блюд',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.TextField(choices=[('WAITING_FOR_COOKING', 'Передано на кухню'), ('COOKING', 'Готовится'), ('WAITING_FOR_DELIVERY', 'Ожидает доставки/готово к выдаче'), ('IN_PROCESS_DELIVERY', 'В процессе доставки'), ('DELIVERED', 'Доставлен'), ('FINISHED', 'Закрыт'), ('CANCELED', 'Отменен'), ('PAID', 'Оплачен')], default='WAITING_FOR_COOKING', verbose_name='Статус заказа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderAndDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('WAITING_FOR_COOKING', 'Ожидает готовки'), ('COOKING', 'Готовится'), ('DONE', 'Готово'), ('CANCELED', 'Отменен'), ('DELIVERED', 'Выдано')], default='WAITING_FOR_COOKING', verbose_name='Статус блюда')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заказ и блюдо',
                'verbose_name_plural': 'Заказы и блюда',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('OPENED', 'Открыт'), ('FINISHED', 'Закрыт'), ('CANCELED', 'Отменен')], default='OPENED', verbose_name='Статус бронирования')),
                ('arrival_time', models.DateTimeField(validators=[apps.orders.models.reservation.validate_arrival_time], verbose_name='Время прибытия')),
            ],
            options={
                'verbose_name': 'Забронированный стол',
                'verbose_name_plural': 'Забронированные столы',
            },
        ),
        migrations.CreateModel(
            name='StopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления ингредиента')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_list', to='orders.ingredient', verbose_name='Отсутствующие ингредиенты')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_list', to='restaurants.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Стоп лист ресторана',
                'verbose_name_plural': 'Стоп листы ресторанов',
            },
        ),
    ]
