# Generated by Django 4.2 on 2024-04-02 15:10

import apps.orders.models.reservation
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.objectfile', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('compound', models.TextField(verbose_name='Состав')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес блюда')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='orders.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название тэга')),
                ('dishes', models.ManyToManyField(related_name='ingredients', to='orders.dish', verbose_name='Блюда с данным ингредиентом')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.TextField(choices=[('WAITING_FOR_COOKING', 'Передано на кухню'), ('COOKING', 'Готовится'), ('WAITING_FOR_DELIVERY', 'Ожидает доставки/готово к выдаче'), ('IN_PROCESS_DELIVERY', 'В процессе доставки'), ('DELIVERED', 'Доставлен/Выдан'), ('FINISHED', 'Закрыт'), ('CANCELED', 'Отменен'), ('PAID', 'Оплачен')], default='WAITING_FOR_COOKING', verbose_name='Статус заказа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('OPENED', 'Открыт'), ('FINISHED', 'Закрыт'), ('CANCELED', 'Отменен')], default='OPENED', verbose_name='Статус бронирования')),
                ('arrival_time', models.DateTimeField(validators=[apps.orders.models.reservation.validate_arrival_time], verbose_name='Время прибытия')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='users.client', verbose_name='Клиент')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.place', verbose_name='Номер места')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Забронированный стол',
                'verbose_name_plural': 'Забронированные столы',
            },
        ),
        migrations.CreateModel(
            name='OrderAndDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.TextField(choices=[('WAITING_FOR_COOKING', 'Ожидает готовки'), ('COOKING', 'Готовится'), ('DONE', 'Готово'), ('CANCELED', 'Отменен'), ('DELIVERED', 'Выдано')], default='WAITING_FOR_COOKING', verbose_name='Статус блюда')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество блюд в заказе')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.dish', verbose_name='Блюдо')),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='users.employee', verbose_name='Исполняющий сотрудник')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ и блюдо',
                'verbose_name_plural': 'Заказы и блюда',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.reservation', verbose_name='Бронирование'),
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.dish', verbose_name='Блюдо')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.objectfile', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка блюда',
                'verbose_name_plural': 'Картинки блюд',
            },
        ),
        migrations.CreateModel(
            name='StopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления ингредиента')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_list', to='orders.ingredient', verbose_name='Отсутствующие ингредиенты')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_list', to='restaurants.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Стоп лист ресторана',
                'verbose_name_plural': 'Стоп листы ресторанов',
                'unique_together': {('ingredient', 'restaurant')},
            },
        ),
    ]
