# Generated by Django 4.2 on 2024-04-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('DELAYED', 'Отложен'), ('WAITING_FOR_COOKING', 'Передан на кухню'), ('COOKING', 'Готовится'), ('WAITING_FOR_DELIVERY', 'Ожидает доставки/готов к выдаче'), ('IN_PROCESS_DELIVERY', 'В процессе доставки'), ('DELIVERED', 'Доставлен/Выдан'), ('FINISHED', 'Закрыт'), ('CANCELED', 'Отменен'), ('PAID', 'Оплачен')], default='WAITING_FOR_COOKING', verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderanddish',
            name='status',
            field=models.TextField(choices=[('WAITING_FOR_COOKING', 'Ожидает готовки'), ('COOKING', 'Готовится'), ('DONE', 'Готов'), ('CANCELED', 'Отменен'), ('DELIVERED', 'Выдан')], default='WAITING_FOR_COOKING', verbose_name='Статус блюда'),
        ),
    ]
