# Generated by Django 4.2 on 2023-12-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='users.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.place', verbose_name='Номер места'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AddField(
            model_name='orderanddish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.dish', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='orderanddish',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='users.employee', verbose_name='Исполняющий сотрудник'),
        ),
        migrations.AddField(
            model_name='orderanddish',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='order',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.reservation', verbose_name='Бронирование'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dishes',
            field=models.ManyToManyField(related_name='ingredients', to='orders.dish', verbose_name='Блюда с данным ингредиентом'),
        ),
        migrations.AddField(
            model_name='dishimage',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.dish', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='dishimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.objectfile', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='orders.category', verbose_name='Категория'),
        ),
        migrations.AlterUniqueTogether(
            name='stoplist',
            unique_together={('ingredient', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='orderanddish',
            unique_together={('dish', 'order')},
        ),
    ]
