# Generated by Django 3.2.16 on 2022-12-27 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoplist',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_list', to='restaurants.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AddField(
            model_name='restaurantandorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_and_order', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='restaurantandorder',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_and_order', to='restaurants.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AddField(
            model_name='orderanddishes',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.dish', verbose_name='Блюдо'),
        ),
    ]
