# Generated by Django 3.2.16 on 2023-10-19 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoplist',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_list', to='restaurants.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='restaurants.place', verbose_name='Номер места'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AddField(
            model_name='orderanddish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.dish', verbose_name='Блюдо'),
        ),
    ]
