# Generated by Django 3.2.16 on 2023-12-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stoplist',
            unique_together={('ingredient', 'restaurant')},
        ),
    ]
