# Generated by Django 4.2 on 2024-04-24 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_alter_orderanddish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderanddish',
            name='count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество блюд в заказе'),
        ),
    ]
