# Generated by Django 3.2.16 on 2023-12-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderanddish',
            name='comment',
        ),
        migrations.AddField(
            model_name='orderanddish',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество блюд в заказе'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
    ]
