# Generated by Django 4.2 on 2024-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderanddish',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderanddish',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
