# Generated by Django 4.2 on 2024-05-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='count_quests',
            new_name='count_guests',
        ),
    ]
