# Generated by Django 3.2.16 on 2023-12-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20231205_2006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderanddish',
            unique_together={('dish', 'order')},
        ),
    ]
