# Generated by Django 4.2 on 2024-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderanddish_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('DELAYED', 'Отложен'), ('WAITING_FOR_COOKING', 'Передан на кухню'), ('COOKING', 'Готовится'), ('WAITING_FOR_DELIVERY', 'Ожидает доставки/готов к выдаче'), ('IN_PROCESS_DELIVERY', 'В процессе доставки'), ('DELIVERED', 'Доставлен/Выдан'), ('PAID', 'Оплачен'), ('FINISHED', 'Закрыт'), ('CANCELED', 'Отменен')], default='WAITING_FOR_COOKING', verbose_name='Статус заказа'),
        ),
    ]
