# Generated by Django 3.2.16 on 2023-10-22 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_surname'),
        ('orders', '0004_auto_20231022_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='users.client', verbose_name='Клиент'),
        ),
    ]
