# Generated by Django 4.2 on 2024-05-11 06:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='count_quests',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество гостей'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tag_to_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.tagtoplace', verbose_name='Тэг к месту'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='restaurants.place', verbose_name='Номер места'),
        ),
    ]
