# Generated by Django 3.2.16 on 2023-10-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_reservation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.TextField(choices=[('OPENED', 'Открыт'), ('FINISHED', 'Закрыт'), ('CANCELED', 'Отменен')], default='OPENED', verbose_name='Статус бронирования'),
        ),
    ]
