# Generated by Django 4.2 on 2024-06-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_reservation_client_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='count_guests',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='tag_to_place',
        ),
    ]
