# Generated by Django 4.2 on 2024-06-14 12:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_reservation_count_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=17, null=True, region=None, verbose_name='Телефонный номер клиента'),
        ),
    ]
