# Generated by Django 3.2.16 on 2023-10-27 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20231027_1531'),
        ('orders', '0006_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.place', verbose_name='Номер места'),
        ),
    ]
