# Generated by Django 4.2 on 2024-06-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_reservation_created_reservation_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='compound',
        ),
    ]
