apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: emenu
spec:
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: ghcr.io/emenu124ru/django:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: django-credentials
        volumeMounts:
          - mountPath: "./server/static"
            name: staticfiles
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
