# Generated by Django 4.2 on 2024-05-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='week_day',
        ),
    ]
