# Generated by Django 4.2 on 2024-03-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[('WORK', 'Рабочая смена'), ('SICK_LEAVE', 'Больничный'), ('VACATION', 'Отпуск'), ('DAY_OFF', 'Выходной')], default='WORK', max_length=64, verbose_name='Тип элемента расписания'),
        ),
    ]
