# Generated by Django 4.2 on 2024-03-10 07:11

import apps.core.models.file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ForeignKey(default=apps.core.models.file.ObjectFile.create_default_object, on_delete=django.db.models.deletion.CASCADE, to='core.objectfile', verbose_name='Фото сотрудника'),
        ),
    ]
