# Generated by Django 4.2 on 2024-03-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='citizenship',
            field=models.TextField(blank=True, default='', verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.TextField(blank=True, default='', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_contract',
            field=models.TextField(blank=True, default='', verbose_name='Трудовой договор'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='medical_checkup',
            field=models.DateField(blank=True, default='', verbose_name='Медицинский осмотр'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='place_of_birth',
            field=models.TextField(blank=True, default='', verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_experience',
            field=models.TextField(blank=True, default='', verbose_name='Стаж работы'),
        ),
    ]
