# Generated by Django 4.2 on 2024-06-02 15:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_schedule_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=17, region=None, unique=True, verbose_name='Телефонный номер'),
        ),
    ]
