# Generated by Django 4.2 on 2024-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_citizenship_alter_employee_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='medical_checkup',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Медицинский осмотр'),
        ),
    ]
